grafana:
  service:
    type: NodePort
    nodePort: 30902

prometheus:
  service:
    type: NodePort
    nodePort: 30900
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "budget-backend-service"
        metrics_path: "/actuator/prometheus"
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: backend-service

alertmanager:
  alertmanagerSpec:
    service:
      type: NodePort
      nodePort: 30903
