apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 30001
    hostPort: 30001
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 30901
    hostPort: 30901
    listenAddress: 127.0.0.1
    protocol: TCP
  role: control-plane
- role: worker
- role: worker
