apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: budget-backend
  namespace: budget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-backend
  template:
    metadata:
      name: backend-deployment
      labels:
        app: budget-backend
    spec:
      containers:
        - name: budget-backend
          image: budget-monorepo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
