apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: budget
spec:
  type: NodePort
  selector:
    app: budget-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
