apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: budget
spec:
  type: NodePort
  selector:
    app: budget-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
