global:
  namespace: budget
  imagePullPolicy: IfNotPresent

frontend:
  replicas: 2
  labels:
    app: budget-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image:
    repository: budget-monorepo-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30000
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m

backend:
  replicas: 2
  labels:
    app: budget-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image:
    repository: budget-monorepo-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    nodePort: 30001
  resources:
    requests:
      memory: 128Mi
      cpu: 500m
    limits:
      memory: 256Mi
      cpu: 1

postgres:
  replicas: 2
  labels:
    app: postgres
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: budget_db
  persistence:
    enabled: true
    size: 2Gi
    storageClass: standard
