apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.labels.app }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.app }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      name: backend-deployment
      labels:
        app: {{ .Values.backend.labels.app }}
    spec:
      containers:
        - name: budget-backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          resources:
            requests:
              memory: {{  .Values.backend.resources.requests.memory }}
              cpu: {{  .Values.backend.resources.requests.cpu }}
            limits:
              memory: {{  .Values.backend.resources.limits.memory }}
              cpu: {{  .Values.backend.resources.limits.cpu }}
