apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
    - port: {{ .Values.backend.service.port }}
      nodePort: {{ .Values.backend.service.nodePort }}
