apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  strategy:
    type: {{ .Values.frontend.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      name: frontend-deployment
      labels:
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
        - name: budget-frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: VITE_BACKEND_URL
              value: "http://backend-service:8080"
          resources:
            requests:
              memory: {{  .Values.frontend.resources.requests.memory }}
              cpu: {{  .Values.frontend.resources.requests.cpu }}
            limits:
              memory: {{  .Values.frontend.resources.limits.memory }}
              cpu: {{  .Values.frontend.resources.limits.cpu }}
