apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.labels.app }}
  ports:
    - port: {{ .Values.postgres.service.port }}
